spring.application.name=backend
spring.datasource.username=
spring.datasource.url=jdbc:postgresql://db.onriuwhxdfwuqdjgkdea.supabase.co:5432/postgres?user=postgres&password=Kokta@1122#
spring.datasource.password=Kokta@1122#
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.default_schema=public
#spring.jpa.properties.hibernate.type.json_format_mapper=jackson
#spring.jpa.properties.hibernate.type.json_format_mapper=org.hibernate.type.format.StringBasedJsonFormatMapper
app.cors.allowed-origins=https://your-app.vercel.app